SELECT * FROM MEMBER;
update member set name = '¼Õ¾Æ' pwd = '7777' where id = '¼Õ¹Î¾Æ';


CREATE TABLE ZEBRA
(
    ID VARCHAR2(50),
    PWD VARCHAR2(50),
    NAME VARCHAR2(50),
    GENDER VARCHAR2(1),
    AGE NUMBER,
    BIRTHDAY VARCHAR2(20),
    PHONE VARCHAR2(13),
    REGDATE DATE,
    EMAIL VARCHAR2(20)
);
SELECT * FROM ZEBRA;

INSERT INTO ZEBRA
(ID, PWD, NAME, GENDER, AGE, BIRTHDAY, PHONE)
VALUES
('MINA','4567','¼Õ¹Î¾Æ','F','27','2021-05-06','010-5288-9999');

INSERT INTO ZEBRA
(ID, PWD, NAME, GENDER)
VALUES
('HEY','1111','À¯ÈÄ','F');

INSERT INTO ZEBRA
(ID, PWD, NAME, GENDER)
VALUES
('QWER','1111','TYY','F');

INSERT INTO ZEBRA
(ID, PWD, NAME, GENDER)
VALUES
('BABY','2222','¸Þ·Õ','F');

SELECT * FROM ZEBRA;

ALTER TABLE ZEBRA MODIFY ID NVARCHAR(40);
ALTER TABLE ZEBRA DROP COLUMN AGE;
ALTER TABLE ZEBRA ADD HOBBY VARCHAR2(200);

CREATE TABLE ROLE
(
    ID VARCHAR2(50),
    DISCRIPTION NVARCHAR2(500),
);